#spring:
#  cloud:
#    gateway:
#      mvc:
#        routes:
#          - id : r1
#            uri: http://localhost:9000/
#            predicates:
#              - Path=/patients/**
#          - id : r2
#            uri: http://localhost:3000/
#            predicates:
#              - Path=/payments/**
#  application:
#    name: GATEWAY-SERVICE
#server:
#  port: 8888