#server:
#  port: 3000
#spring:
#  application:
#    name: PAYMENT-SERVICE
#  datasource:
#    url: jdbc:h2:file:./payment/database/payment_db
#    driverClassName: org.h2.Driver
#    username: root
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#  h2:
#    console:
#      enabled: true
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true
